//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyPlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public System.DateTime ReminderTime { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
